### ISSUE TITLE
api Return 501 if service not deployed in state

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#77] opened 2015-04-23 21:00 UTC
api/[ma | mk] user, setLanguage
api/kilkari user, inbox, subscription

**Comment by larubbio** [comment] 2015-04-25 00:31
I'm tempted to move this to Sprint 2.  I think we need to look at the State - Circle mapping in the SRS and implement that before this.  

We also have some work to do on the backend of the get user api calls according to NMS.GEN.LANG.004

I assume if a user exists we can check their state.  If no user then we use circle to find the state.  If multiple states in the circle then we wait for the users languageLocationCode to find the actual state.

**Comment by frankhuster** [comment] 2015-04-25 05:01
Agreed, looks to me like Spring2 territory.

**Comment by llavoie** [comment] 2015-04-25 19:31
Ok, I moved it.

**Comment by llavoie** [comment] 2015-04-27 18:54
Duplicate of #133

**Closed by llavoie** 2015-04-27 18:54 UTC
