### ISSUE TITLE
NMS.GEN.DEPL.001 - Allow State by State or Service by Service rollout

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#133] opened 2015-04-25 23:48 UTC
The NMS system shall ensure that various services can be deployed in phased manner across states. 
The phasing shall be both service-wise and state-wise (i.e. it shall not be necessary to deploy all 3 services in a state to start with).

It shall not be necessary that content of all states are ready at the time of deployment.

**Comment by llavoie** [comment] 2015-05-14 22:23
Duplicate of #134

**Closed by llavoie** 2015-05-14 22:23 UTC
Labels: 3.3.2 Deployment Requirements, duplicate, FT2
